apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-db
  name: {{ .Release.Name }}-db
spec:
  ports:
  - port: {{ .Values.db.port }}
    protocol: TCP
    targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Release.Name }}-db
  type: ClusterIP
  clusterIP: None
