apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: code-server
    port: {{ .Values.workspace.port }}
    protocol: TCP
    targetPort: {{ .Values.workspace.port }}
  - name: app
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
