apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-db
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.db.image }}"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password }}
        ports:
        - name: postgres
          containerPort: {{ .Values.db.port }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: default
      resources:
        requests:
          storage: {{ .Values.db.size }}
