version: '3.9'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    command: sleep infinity
    volumes:
    - ../:/workspace
    ports:
    - 8080:8080
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
